export const LookUpKeys = {
    regions: "regions",
    damageType: "damage_type",
    dealerType: "dealer_type",
    yard: "yard",
    ageLeadTime: "age_lead_time",
    legalStatus: "legal_status",
    gender: "gender",
    contactType: "contact_type",
    purchasingType: "purchasing_type",
    purchasingPurpose: "purchasing_purpose",
    cancelReason: "cancel_reason",
    gasolineType: "gasoline_type",
    drivingType: "driving_type",
    useStatus: "use_status",
    logisticWay: "logistic_way",
    transportFrom: "Transport_From",
    yardLocation: "yard_location",
    audio: "audio",
    businessField: "BUSINESS_FIELD",
    paymentType: "payment_type",
    monthXXX: "month_xxx",
    form: "form",
    bankType: "bank_type",
    day: "day",
    volumnRange: "volumn_range",
    month: "month",
    year: "year",
    estimatedReason: "estimated_reason",
    lexusArrivalPort: "lexus_arrival_port",
    vehicleStatus: "vehicle_status",
    salesDealer: "sales_dealer",
    yardId: "yard_id",
    invoiceRequestDateDeadline: "invoice_request_date_deadline",
    saleDateDeadline: "sale_date_deadline",
    selfDrivingTripDeadline: "self_driving_trip_deadline",
    lexusMarineMode: "lexus_marine_mode",
    dlrSubRegion: "dlr_sub_region",
    portRegion: "port_region",
    saleLockLastDomTime: "sale_lock_last_dom_time",
    saleLocMonth: "sale_lock_month",
    saleLockSalePersonDate: "sale_lock_sale_person_date",
    cbuckd: "cbuckd",
    paymentBy: "payment_by",
    fromGroupDelivery: "Delivery_From_Group",
    swapVehicleSell: "swap_vehicle_sell",
    adminTable: "admin_table",
    swapStatus: "swap_status",
    groupType: "Group_type",
    tmv: "TMV",
    cbuCkdStatus: "cbuCkdStatus",
    salesStatus: "sales_status",
    carStatus: "car_status",
    swaprequestdate: "swap_request_date",
    swapchangetype: "swap_change_type",
    reasonOfNA: "reason-of-na",
    sourceOfAccessories: "source-of-accessories",
    accessories_package_purchase: "accessories_package_purchase",
    swapTransStatus: "swap_vehicle_buy",
    supporterType: "supporter_type",
    swapVehicleType: "swap_vehicle_type",
    kindOfSwap: "kind_of_swap",
    empGender: "emp_gender",
    marriedState: "married_state",
    contractType: "contract_type",
    tTepSchool: "t_tep_school",
    tTepBranch: "t_tep_branch",
    empState: "emp_state",
    quitJobTemporary: "quit_job_temporary",
    quitJobReason: "quit_job_reason",
    vehicleProductType: "vehicle_product_type",
    vehicleProductDocument: "vehicle_product_document",
    manufactor_made_in: "manufactor_made_in",
    promotionType: "promotion_type",
    generalFunctionRole: "general_function_role",
    folderType: "folder_type",
    insuranceLevel: "insurance_level",
    fleetCustomerType: "fleet_customer_type",
    fleetBussinessType: "fleet_bussiness_type",
    fleetStatus: "fleet_status",
    fleetType: "fleet_type",
    fleetRepresentative: "fleet_representative",
    fleetTitle: "fleet_title",
    schemeType: "scheme_type",
    schemeSource: "scheme_source",
    schemeScore: "scheme_score",
    transactionType: "transaction_type",
    rankStatus: "rank_status",
    versionType: "version_type",
    sourceType: "source_type",
    sourceTypeId: "source_type_id",
    statusId: "claim_status",
    sourceId: "redeem_sourceId",
    fleetVersion: "fleet_version",
    dealerTmv: "dealer_tmv",
    promotionSource:"promotion_source",
    fsoGradeCbuCkd:"cbuckd_grade_submit",
    loyaltyExpensiveType:"loyalty_expense_type",
    vehicleSaleStatus:"vehicle_sale_status",
    index: "index",
    fsoIndex: "fso_index",
    bonusScoreType:"bonus_score_type",
    materialType: "material_type",
    categoryName: "category_name",
    accessoryType: "accessory_type",
    bannerCode: "banner_code",
    registerStatus: "register_status",
    configstatus: "config_status",
    redeemPlace:"redeem_place",
    redeemStatus:"redeem_status",
    approveStatus: "approve_status",
    giftType: "gift_type",
    addScoreType:"add_score_type",
    vehicleSourceFleet:"vehicle_source_fleet",
    imageTypes:"image_types",
    emailType: "email_type",
    ratioCost: 'ratio_cost'
};
