export const TABS = {
    // Admin

    ADMIN_ORGANIZATION_UNITS: 'ADMIN_ORGANIZATION_UNITS',
    ADMIN_USERS: 'ADMIN_USERS',
    ADMIN_ROLES: 'ADMIN_ROLES',









    //Master Sales
    MASTER_SALE_PROVINCE: 'MASTER_SALE_PROVINCE',
    MASTER_SALE_DISTRICT: 'MASTER_SALE_DISTRICT',
    STUDENT: 'STUDENT',
    BUILDING_ROOM: 'BUILDING_ROOM',
    INVOICE: 'INVOICE',
    INBILL: 'INBILL',
    OUTBILL: 'OUTBILL',
    CONTRACT: 'CONTRACT',


    //SALES



}
